default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lucysight_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: lucysight_test

production:
  <<: *default
  database: lucysight_production
